platform :ios, '14.1'
use_frameworks!

# Map custom build configurations to CocoaPods presets
# so pod install generates the correct xcconfig files
project 'iosApp.xcodeproj', {
  'Debug' => :debug,
  'Debug-Local' => :debug,
  'Release' => :release
}

target 'iosApp' do
  # ComposeApp framework from Kotlin Multiplatform
  pod 'composeApp', :path => '../composeApp'

  # Note: Mapbox Maps SDK is now added via Swift Package Manager
  # Add it in Xcode: File > Add Package Dependencies
  # URL: https://github.com/mapbox/mapbox-maps-ios.git
  # Version: 11.18.0 or later
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Ensure minimum iOS 12.0 for all pods (Xcode requirement)
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
      config.build_settings['SWIFT_VERSION'] = '5.9'
    end
  end
end
