platform :ios, '14.1'
use_frameworks!

target 'iosApp' do
  pod 'composeApp', :path => '../composeApp'
  pod 'MapboxMaps', '~> 10.16.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['SWIFT_VERSION'] = '5.9'
    end
  end
end
